name: Delete Pre-releases

on:
  workflow_dispatch:

permissions:
  contents: write       # write to allow deleting Releases and tags

jobs:
  delete-prereleases:
    # Deletes all pre-releases and their tags.
    # Shared across projects: https://github.com/LukeNeedham/ci-workflows
    uses: LukeNeedham/ci-workflows/.github/workflows/delete_prereleases.yml@main
